#-------------------------------------------------------------------------------------------------------
# Copyright (c) ChakraCore Project Contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
#-------------------------------------------------------------------------------------------------------

task:
  name: CMake ARM64.macOS.Debug (noJit)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode
  Dependencies_script:  brew install ninja icu4c && mkdir -p build
  CMake_script: cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DSTATIC_LIBRARY=ON -DICU_INCLUDE_PATH=/opt/homebrew/opt/icu4c/include -DDISABLE_JIT=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
  Build_script: cd build && ninja
  Test_script: cd build && ninja check

task:
  name: CMake ARM64.macOS.ReleaseWithDebug (noJit)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode
  Dependencies_script:  brew install ninja icu4c && mkdir -p build
  CMake_script: cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DICU_INCLUDE_PATH=/opt/homebrew/opt/icu4c/include -DDISABLE_JIT=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
  Build_script: cd build && ninja
  Test_script: cd build && ninja check

task:
  name: CMake ARM64.macOS.Release (noJit)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode
  Dependencies_script:  brew install ninja icu4c && mkdir -p build
  CMake_script: cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DSTATIC_LIBRARY=ON -DICU_INCLUDE_PATH=/opt/homebrew/opt/icu4c/include -DDISABLE_JIT=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..
  Build_script: cd build && ninja
  Test_script: cd build && ninja check
