//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------

DEBUGOBJECTPROPERTY(arguments)
DEBUGOBJECTPROPERTY(breakpointId)
DEBUGOBJECTPROPERTY(className)
DEBUGOBJECTPROPERTY(column)
DEBUGOBJECTPROPERTY(debuggerOnlyProperties)
DEBUGOBJECTPROPERTY(display)
DEBUGOBJECTPROPERTY(error)
DEBUGOBJECTPROPERTY(exception)
DEBUGOBJECTPROPERTY(fileName)
DEBUGOBJECTPROPERTY(firstStatementColumn)
DEBUGOBJECTPROPERTY(firstStatementLine)
DEBUGOBJECTPROPERTY(functionCallsReturn)
DEBUGOBJECTPROPERTY(functionHandle)
DEBUGOBJECTPROPERTY(globals)
DEBUGOBJECTPROPERTY(handle)
DEBUGOBJECTPROPERTY(index)
DEBUGOBJECTPROPERTY(line)
DEBUGOBJECTPROPERTY(lineCount)
DEBUGOBJECTPROPERTY(locals)
DEBUGOBJECTPROPERTY(name)
DEBUGOBJECTPROPERTY(parentScriptId)
DEBUGOBJECTPROPERTY(properties)
DEBUGOBJECTPROPERTY(propertyAttributes)
DEBUGOBJECTPROPERTY(returnValue)
DEBUGOBJECTPROPERTY(scopes)
DEBUGOBJECTPROPERTY(scriptHandle)
DEBUGOBJECTPROPERTY(scriptId)
DEBUGOBJECTPROPERTY(scriptType)
DEBUGOBJECTPROPERTY(source)
DEBUGOBJECTPROPERTY(sourceLength)
DEBUGOBJECTPROPERTY(sourceText)
DEBUGOBJECTPROPERTY(thisObject)
DEBUGOBJECTPROPERTY(totalPropertiesOfObject)
DEBUGOBJECTPROPERTY(type)
DEBUGOBJECTPROPERTY(uncaught)
DEBUGOBJECTPROPERTY(value)
#undef DEBUGOBJECTPROPERTY
