//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------

// This file was generated by tools/specialcasings.py using
// SpecialCasing.txt from ftp://ftp.unicode.org/Public/10.0.0/ucd/SpecialCasing.txt

var SpecialCasings = [
    {
        "code": "\u00DF", 
        "lower": "\u00DF", 
        "name": "LATIN SMALL LETTER SHARP S", 
        "upper": "\u0053\u0053"
    }, 
    {
        "code": "\u0130", 
        "lower": "\u0069\u0307", 
        "name": "LATIN CAPITAL LETTER I WITH DOT ABOVE", 
        "upper": "\u0130"
    }, 
    {
        "code": "\uFB00", 
        "lower": "\uFB00", 
        "name": "LATIN SMALL LIGATURE FF", 
        "upper": "\u0046\u0046"
    }, 
    {
        "code": "\uFB01", 
        "lower": "\uFB01", 
        "name": "LATIN SMALL LIGATURE FI", 
        "upper": "\u0046\u0049"
    }, 
    {
        "code": "\uFB02", 
        "lower": "\uFB02", 
        "name": "LATIN SMALL LIGATURE FL", 
        "upper": "\u0046\u004C"
    }, 
    {
        "code": "\uFB03", 
        "lower": "\uFB03", 
        "name": "LATIN SMALL LIGATURE FFI", 
        "upper": "\u0046\u0046\u0049"
    }, 
    {
        "code": "\uFB04", 
        "lower": "\uFB04", 
        "name": "LATIN SMALL LIGATURE FFL", 
        "upper": "\u0046\u0046\u004C"
    }, 
    {
        "code": "\uFB05", 
        "lower": "\uFB05", 
        "name": "LATIN SMALL LIGATURE LONG S T", 
        "upper": "\u0053\u0054"
    }, 
    {
        "code": "\uFB06", 
        "lower": "\uFB06", 
        "name": "LATIN SMALL LIGATURE ST", 
        "upper": "\u0053\u0054"
    }, 
    {
        "code": "\u0587", 
        "lower": "\u0587", 
        "name": "ARMENIAN SMALL LIGATURE ECH YIWN", 
        "upper": "\u0535\u0552"
    }, 
    {
        "code": "\uFB13", 
        "lower": "\uFB13", 
        "name": "ARMENIAN SMALL LIGATURE MEN NOW", 
        "upper": "\u0544\u0546"
    }, 
    {
        "code": "\uFB14", 
        "lower": "\uFB14", 
        "name": "ARMENIAN SMALL LIGATURE MEN ECH", 
        "upper": "\u0544\u0535"
    }, 
    {
        "code": "\uFB15", 
        "lower": "\uFB15", 
        "name": "ARMENIAN SMALL LIGATURE MEN INI", 
        "upper": "\u0544\u053B"
    }, 
    {
        "code": "\uFB16", 
        "lower": "\uFB16", 
        "name": "ARMENIAN SMALL LIGATURE VEW NOW", 
        "upper": "\u054E\u0546"
    }, 
    {
        "code": "\uFB17", 
        "lower": "\uFB17", 
        "name": "ARMENIAN SMALL LIGATURE MEN XEH", 
        "upper": "\u0544\u053D"
    }, 
    {
        "code": "\u0149", 
        "lower": "\u0149", 
        "name": "LATIN SMALL LETTER N PRECEDED BY APOSTROPHE", 
        "upper": "\u02BC\u004E"
    }, 
    {
        "code": "\u0390", 
        "lower": "\u0390", 
        "name": "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS", 
        "upper": "\u0399\u0308\u0301"
    }, 
    {
        "code": "\u03B0", 
        "lower": "\u03B0", 
        "name": "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS", 
        "upper": "\u03A5\u0308\u0301"
    }, 
    {
        "code": "\u01F0", 
        "lower": "\u01F0", 
        "name": "LATIN SMALL LETTER J WITH CARON", 
        "upper": "\u004A\u030C"
    }, 
    {
        "code": "\u1E96", 
        "lower": "\u1E96", 
        "name": "LATIN SMALL LETTER H WITH LINE BELOW", 
        "upper": "\u0048\u0331"
    }, 
    {
        "code": "\u1E97", 
        "lower": "\u1E97", 
        "name": "LATIN SMALL LETTER T WITH DIAERESIS", 
        "upper": "\u0054\u0308"
    }, 
    {
        "code": "\u1E98", 
        "lower": "\u1E98", 
        "name": "LATIN SMALL LETTER W WITH RING ABOVE", 
        "upper": "\u0057\u030A"
    }, 
    {
        "code": "\u1E99", 
        "lower": "\u1E99", 
        "name": "LATIN SMALL LETTER Y WITH RING ABOVE", 
        "upper": "\u0059\u030A"
    }, 
    {
        "code": "\u1E9A", 
        "lower": "\u1E9A", 
        "name": "LATIN SMALL LETTER A WITH RIGHT HALF RING", 
        "upper": "\u0041\u02BE"
    }, 
    {
        "code": "\u1F50", 
        "lower": "\u1F50", 
        "name": "GREEK SMALL LETTER UPSILON WITH PSILI", 
        "upper": "\u03A5\u0313"
    }, 
    {
        "code": "\u1F52", 
        "lower": "\u1F52", 
        "name": "GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA", 
        "upper": "\u03A5\u0313\u0300"
    }, 
    {
        "code": "\u1F54", 
        "lower": "\u1F54", 
        "name": "GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA", 
        "upper": "\u03A5\u0313\u0301"
    }, 
    {
        "code": "\u1F56", 
        "lower": "\u1F56", 
        "name": "GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI", 
        "upper": "\u03A5\u0313\u0342"
    }, 
    {
        "code": "\u1FB6", 
        "lower": "\u1FB6", 
        "name": "GREEK SMALL LETTER ALPHA WITH PERISPOMENI", 
        "upper": "\u0391\u0342"
    }, 
    {
        "code": "\u1FC6", 
        "lower": "\u1FC6", 
        "name": "GREEK SMALL LETTER ETA WITH PERISPOMENI", 
        "upper": "\u0397\u0342"
    }, 
    {
        "code": "\u1FD2", 
        "lower": "\u1FD2", 
        "name": "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA", 
        "upper": "\u0399\u0308\u0300"
    }, 
    {
        "code": "\u1FD3", 
        "lower": "\u1FD3", 
        "name": "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA", 
        "upper": "\u0399\u0308\u0301"
    }, 
    {
        "code": "\u1FD6", 
        "lower": "\u1FD6", 
        "name": "GREEK SMALL LETTER IOTA WITH PERISPOMENI", 
        "upper": "\u0399\u0342"
    }, 
    {
        "code": "\u1FD7", 
        "lower": "\u1FD7", 
        "name": "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI", 
        "upper": "\u0399\u0308\u0342"
    }, 
    {
        "code": "\u1FE2", 
        "lower": "\u1FE2", 
        "name": "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA", 
        "upper": "\u03A5\u0308\u0300"
    }, 
    {
        "code": "\u1FE3", 
        "lower": "\u1FE3", 
        "name": "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA", 
        "upper": "\u03A5\u0308\u0301"
    }, 
    {
        "code": "\u1FE4", 
        "lower": "\u1FE4", 
        "name": "GREEK SMALL LETTER RHO WITH PSILI", 
        "upper": "\u03A1\u0313"
    }, 
    {
        "code": "\u1FE6", 
        "lower": "\u1FE6", 
        "name": "GREEK SMALL LETTER UPSILON WITH PERISPOMENI", 
        "upper": "\u03A5\u0342"
    }, 
    {
        "code": "\u1FE7", 
        "lower": "\u1FE7", 
        "name": "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI", 
        "upper": "\u03A5\u0308\u0342"
    }, 
    {
        "code": "\u1FF6", 
        "lower": "\u1FF6", 
        "name": "GREEK SMALL LETTER OMEGA WITH PERISPOMENI", 
        "upper": "\u03A9\u0342"
    }, 
    {
        "code": "\u1F80", 
        "lower": "\u1F80", 
        "name": "GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI", 
        "upper": "\u1F08\u0399"
    }, 
    {
        "code": "\u1F81", 
        "lower": "\u1F81", 
        "name": "GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI", 
        "upper": "\u1F09\u0399"
    }, 
    {
        "code": "\u1F82", 
        "lower": "\u1F82", 
        "name": "GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1F0A\u0399"
    }, 
    {
        "code": "\u1F83", 
        "lower": "\u1F83", 
        "name": "GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1F0B\u0399"
    }, 
    {
        "code": "\u1F84", 
        "lower": "\u1F84", 
        "name": "GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI", 
        "upper": "\u1F0C\u0399"
    }, 
    {
        "code": "\u1F85", 
        "lower": "\u1F85", 
        "name": "GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI", 
        "upper": "\u1F0D\u0399"
    }, 
    {
        "code": "\u1F86", 
        "lower": "\u1F86", 
        "name": "GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u1F0E\u0399"
    }, 
    {
        "code": "\u1F87", 
        "lower": "\u1F87", 
        "name": "GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u1F0F\u0399"
    }, 
    {
        "code": "\u1F88", 
        "lower": "\u1F80", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI", 
        "upper": "\u1F08\u0399"
    }, 
    {
        "code": "\u1F89", 
        "lower": "\u1F81", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI", 
        "upper": "\u1F09\u0399"
    }, 
    {
        "code": "\u1F8A", 
        "lower": "\u1F82", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI", 
        "upper": "\u1F0A\u0399"
    }, 
    {
        "code": "\u1F8B", 
        "lower": "\u1F83", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI", 
        "upper": "\u1F0B\u0399"
    }, 
    {
        "code": "\u1F8C", 
        "lower": "\u1F84", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI", 
        "upper": "\u1F0C\u0399"
    }, 
    {
        "code": "\u1F8D", 
        "lower": "\u1F85", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI", 
        "upper": "\u1F0D\u0399"
    }, 
    {
        "code": "\u1F8E", 
        "lower": "\u1F86", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI", 
        "upper": "\u1F0E\u0399"
    }, 
    {
        "code": "\u1F8F", 
        "lower": "\u1F87", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI", 
        "upper": "\u1F0F\u0399"
    }, 
    {
        "code": "\u1F90", 
        "lower": "\u1F90", 
        "name": "GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI", 
        "upper": "\u1F28\u0399"
    }, 
    {
        "code": "\u1F91", 
        "lower": "\u1F91", 
        "name": "GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI", 
        "upper": "\u1F29\u0399"
    }, 
    {
        "code": "\u1F92", 
        "lower": "\u1F92", 
        "name": "GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1F2A\u0399"
    }, 
    {
        "code": "\u1F93", 
        "lower": "\u1F93", 
        "name": "GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1F2B\u0399"
    }, 
    {
        "code": "\u1F94", 
        "lower": "\u1F94", 
        "name": "GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI", 
        "upper": "\u1F2C\u0399"
    }, 
    {
        "code": "\u1F95", 
        "lower": "\u1F95", 
        "name": "GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI", 
        "upper": "\u1F2D\u0399"
    }, 
    {
        "code": "\u1F96", 
        "lower": "\u1F96", 
        "name": "GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u1F2E\u0399"
    }, 
    {
        "code": "\u1F97", 
        "lower": "\u1F97", 
        "name": "GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u1F2F\u0399"
    }, 
    {
        "code": "\u1F98", 
        "lower": "\u1F90", 
        "name": "GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI", 
        "upper": "\u1F28\u0399"
    }, 
    {
        "code": "\u1F99", 
        "lower": "\u1F91", 
        "name": "GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI", 
        "upper": "\u1F29\u0399"
    }, 
    {
        "code": "\u1F9A", 
        "lower": "\u1F92", 
        "name": "GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI", 
        "upper": "\u1F2A\u0399"
    }, 
    {
        "code": "\u1F9B", 
        "lower": "\u1F93", 
        "name": "GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI", 
        "upper": "\u1F2B\u0399"
    }, 
    {
        "code": "\u1F9C", 
        "lower": "\u1F94", 
        "name": "GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI", 
        "upper": "\u1F2C\u0399"
    }, 
    {
        "code": "\u1F9D", 
        "lower": "\u1F95", 
        "name": "GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI", 
        "upper": "\u1F2D\u0399"
    }, 
    {
        "code": "\u1F9E", 
        "lower": "\u1F96", 
        "name": "GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI", 
        "upper": "\u1F2E\u0399"
    }, 
    {
        "code": "\u1F9F", 
        "lower": "\u1F97", 
        "name": "GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI", 
        "upper": "\u1F2F\u0399"
    }, 
    {
        "code": "\u1FA0", 
        "lower": "\u1FA0", 
        "name": "GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI", 
        "upper": "\u1F68\u0399"
    }, 
    {
        "code": "\u1FA1", 
        "lower": "\u1FA1", 
        "name": "GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI", 
        "upper": "\u1F69\u0399"
    }, 
    {
        "code": "\u1FA2", 
        "lower": "\u1FA2", 
        "name": "GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1F6A\u0399"
    }, 
    {
        "code": "\u1FA3", 
        "lower": "\u1FA3", 
        "name": "GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1F6B\u0399"
    }, 
    {
        "code": "\u1FA4", 
        "lower": "\u1FA4", 
        "name": "GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI", 
        "upper": "\u1F6C\u0399"
    }, 
    {
        "code": "\u1FA5", 
        "lower": "\u1FA5", 
        "name": "GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI", 
        "upper": "\u1F6D\u0399"
    }, 
    {
        "code": "\u1FA6", 
        "lower": "\u1FA6", 
        "name": "GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u1F6E\u0399"
    }, 
    {
        "code": "\u1FA7", 
        "lower": "\u1FA7", 
        "name": "GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u1F6F\u0399"
    }, 
    {
        "code": "\u1FA8", 
        "lower": "\u1FA0", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI", 
        "upper": "\u1F68\u0399"
    }, 
    {
        "code": "\u1FA9", 
        "lower": "\u1FA1", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI", 
        "upper": "\u1F69\u0399"
    }, 
    {
        "code": "\u1FAA", 
        "lower": "\u1FA2", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI", 
        "upper": "\u1F6A\u0399"
    }, 
    {
        "code": "\u1FAB", 
        "lower": "\u1FA3", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI", 
        "upper": "\u1F6B\u0399"
    }, 
    {
        "code": "\u1FAC", 
        "lower": "\u1FA4", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI", 
        "upper": "\u1F6C\u0399"
    }, 
    {
        "code": "\u1FAD", 
        "lower": "\u1FA5", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI", 
        "upper": "\u1F6D\u0399"
    }, 
    {
        "code": "\u1FAE", 
        "lower": "\u1FA6", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI", 
        "upper": "\u1F6E\u0399"
    }, 
    {
        "code": "\u1FAF", 
        "lower": "\u1FA7", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI", 
        "upper": "\u1F6F\u0399"
    }, 
    {
        "code": "\u1FB3", 
        "lower": "\u1FB3", 
        "name": "GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI", 
        "upper": "\u0391\u0399"
    }, 
    {
        "code": "\u1FBC", 
        "lower": "\u1FB3", 
        "name": "GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI", 
        "upper": "\u0391\u0399"
    }, 
    {
        "code": "\u1FC3", 
        "lower": "\u1FC3", 
        "name": "GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI", 
        "upper": "\u0397\u0399"
    }, 
    {
        "code": "\u1FCC", 
        "lower": "\u1FC3", 
        "name": "GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI", 
        "upper": "\u0397\u0399"
    }, 
    {
        "code": "\u1FF3", 
        "lower": "\u1FF3", 
        "name": "GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI", 
        "upper": "\u03A9\u0399"
    }, 
    {
        "code": "\u1FFC", 
        "lower": "\u1FF3", 
        "name": "GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI", 
        "upper": "\u03A9\u0399"
    }, 
    {
        "code": "\u1FB2", 
        "lower": "\u1FB2", 
        "name": "GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1FBA\u0399"
    }, 
    {
        "code": "\u1FB4", 
        "lower": "\u1FB4", 
        "name": "GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI", 
        "upper": "\u0386\u0399"
    }, 
    {
        "code": "\u1FC2", 
        "lower": "\u1FC2", 
        "name": "GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1FCA\u0399"
    }, 
    {
        "code": "\u1FC4", 
        "lower": "\u1FC4", 
        "name": "GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI", 
        "upper": "\u0389\u0399"
    }, 
    {
        "code": "\u1FF2", 
        "lower": "\u1FF2", 
        "name": "GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI", 
        "upper": "\u1FFA\u0399"
    }, 
    {
        "code": "\u1FF4", 
        "lower": "\u1FF4", 
        "name": "GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI", 
        "upper": "\u038F\u0399"
    }, 
    {
        "code": "\u1FB7", 
        "lower": "\u1FB7", 
        "name": "GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u0391\u0342\u0399"
    }, 
    {
        "code": "\u1FC7", 
        "lower": "\u1FC7", 
        "name": "GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u0397\u0342\u0399"
    }, 
    {
        "code": "\u1FF7", 
        "lower": "\u1FF7", 
        "name": "GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI", 
        "upper": "\u03A9\u0342\u0399"
    }
];