//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft Corporation and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
/*
 * These are javascript library functions that might be inlined
 * by the JIT.
 *
 * Notes:
 * - the argc is the number of args to pass to InlineXXX call, e.g. 2 for Math.pow and 2 for String.CharAt.
 * - TODO: consider having dst/src1/src2 in separate columns rather than bitmask, this seems to be better for design but we won't be able to see 'all float' by single check.
 * - TODO: enable string inlines when string type spec is available
 *
 *               target         name                argc  flags                                               EntryInfo
 */
LIBRARY_FUNCTION(Math,          Abs,                1,    BIF_TypeSpecSrcAndDstToFloatOrInt                 , Math::EntryInfo::Abs)
LIBRARY_FUNCTION(Math,          Acos,               1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Acos)
LIBRARY_FUNCTION(Math,          Asin,               1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Asin)
LIBRARY_FUNCTION(Math,          Atan,               1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Atan)
LIBRARY_FUNCTION(Math,          Atan2,              2,    BIF_TypeSpecAllToFloat                            , Math::EntryInfo::Atan2)
LIBRARY_FUNCTION(Math,          Ceil,               1,    BIF_TypeSpecDstToInt | BIF_TypeSpecSrc1ToFloat    , Math::EntryInfo::Ceil)
LIBRARY_FUNCTION(String,        CodePointAt,        2,    BIF_TypeSpecSrc2ToInt | BIF_UseSrc0               , JavascriptString::EntryInfo::CodePointAt)
LIBRARY_FUNCTION(String,        CharAt,             2,    BIF_UseSrc0                                       , JavascriptString::EntryInfo::CharAt  )
LIBRARY_FUNCTION(String,        CharCodeAt,         2,    BIF_UseSrc0                                       , JavascriptString::EntryInfo::CharCodeAt )
LIBRARY_FUNCTION(String,        Concat,             15,   BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptString::EntryInfo::Concat )
LIBRARY_FUNCTION(String,        FromCharCode,       1,    BIF_None                                          , JavascriptString::EntryInfo::FromCharCode)
LIBRARY_FUNCTION(String,        FromCodePoint,      1,    BIF_None                                          , JavascriptString::EntryInfo::FromCodePoint)
LIBRARY_FUNCTION(String,        IndexOf,            3,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptString::EntryInfo::IndexOf)
LIBRARY_FUNCTION(String,        LastIndexOf,        3,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptString::EntryInfo::LastIndexOf)
LIBRARY_FUNCTION(String,        Link,               2,    BIF_UseSrc0                                       , JavascriptString::EntryInfo::Link)
LIBRARY_FUNCTION(String,        LocaleCompare,      2,    BIF_UseSrc0                                       , JavascriptString::EntryInfo::LocaleCompare)
LIBRARY_FUNCTION(String,        Match,              2,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::Match)
LIBRARY_FUNCTION(String,        Replace,            3,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::Replace)
LIBRARY_FUNCTION(String,        Search,             2,    BIF_UseSrc0                                       , JavascriptString::EntryInfo::Search)
LIBRARY_FUNCTION(String,        Slice,              3,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptString::EntryInfo::Slice )
LIBRARY_FUNCTION(String,        Split,              3,    BIF_UseSrc0 | BIF_VariableArgsNumber | BIF_IgnoreDst , JavascriptString::EntryInfo::Split)
LIBRARY_FUNCTION(String,        Substr,             3,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptString::EntryInfo::Substr)
LIBRARY_FUNCTION(String,        Substring,          3,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptString::EntryInfo::Substring)
LIBRARY_FUNCTION(String,        ToLocaleLowerCase,  1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::ToLocaleLowerCase)
LIBRARY_FUNCTION(String,        ToLocaleUpperCase,  1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::ToLocaleUpperCase)
LIBRARY_FUNCTION(String,        ToLowerCase,        1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::ToLowerCase)
LIBRARY_FUNCTION(String,        ToUpperCase,        1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::ToUpperCase)
LIBRARY_FUNCTION(String,        Trim,               1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::Trim)
LIBRARY_FUNCTION(String,        TrimLeft,           1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::TrimLeft)
LIBRARY_FUNCTION(String,        TrimRight,          1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptString::EntryInfo::TrimRight)
LIBRARY_FUNCTION(Math,          Cos,                1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Cos)
LIBRARY_FUNCTION(Math,          Exp,                1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Exp)
LIBRARY_FUNCTION(Math,          Floor,              1,    BIF_TypeSpecDstToInt | BIF_TypeSpecSrc1ToFloat    , Math::EntryInfo::Floor)
LIBRARY_FUNCTION(Math,          Log,                1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Log)
LIBRARY_FUNCTION(Math,          Max,                2,    BIF_TypeSpecSrcAndDstToFloatOrInt                 , Math::EntryInfo::Max)
LIBRARY_FUNCTION(Math,          Min,                2,    BIF_TypeSpecSrcAndDstToFloatOrInt                 , Math::EntryInfo::Min)
LIBRARY_FUNCTION(Math,          Pow,                2,    BIF_TypeSpecSrcAndDstToFloatOrInt                 , Math::EntryInfo::Pow)
LIBRARY_FUNCTION(Math,          Imul,               2,    BIF_TypeSpecAllToInt                              , Math::EntryInfo::Imul)
LIBRARY_FUNCTION(Math,          Clz32,              1,    BIF_TypeSpecAllToInt                              , Math::EntryInfo::Clz32)
LIBRARY_FUNCTION(Array,         Push,               2,    BIF_UseSrc0 | BIF_IgnoreDst | BIF_TypeSpecSrc1ToFloatOrInt, JavascriptArray::EntryInfo::Push)
LIBRARY_FUNCTION(Array,         Pop,                1,    BIF_UseSrc0 | BIF_TypeSpecDstToFloatOrInt         , JavascriptArray::EntryInfo::Pop)
LIBRARY_FUNCTION(Math,          Random,             0,    BIF_TypeSpecDstToFloat                            , Math::EntryInfo::Random)
LIBRARY_FUNCTION(Math,          Round,              1,    BIF_TypeSpecDstToInt | BIF_TypeSpecSrc1ToFloat    , Math::EntryInfo::Round)
LIBRARY_FUNCTION(Math,          Sin,                1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Sin)
LIBRARY_FUNCTION(Math,          Sqrt,               1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Sqrt)
LIBRARY_FUNCTION(Math,          Tan,                1,    BIF_TypeSpecUnaryToFloat                          , Math::EntryInfo::Tan)
LIBRARY_FUNCTION(Array,         Concat,             15,   BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptArray::EntryInfo::Concat)
LIBRARY_FUNCTION(Array,         IndexOf,            2,    BIF_UseSrc0                                       , JavascriptArray::EntryInfo::IndexOf)
LIBRARY_FUNCTION(Array,         Includes,           2,    BIF_UseSrc0                                       , JavascriptArray::EntryInfo::Includes)
LIBRARY_FUNCTION(Array,         IsArray,            1,    BIF_VariableArgsNumber                            , JavascriptArray::EntryInfo::IsArray)
LIBRARY_FUNCTION(Array,         Join,               2,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptArray::EntryInfo::Join)
LIBRARY_FUNCTION(Array,         LastIndexOf,        3,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptArray::EntryInfo::LastIndexOf)
LIBRARY_FUNCTION(Array,         Reverse,            1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptArray::EntryInfo::Reverse)
LIBRARY_FUNCTION(Array,         Shift,              1,    BIF_UseSrc0 | BIF_IgnoreDst                       , JavascriptArray::EntryInfo::Shift)
LIBRARY_FUNCTION(Array,         Slice,              3,    BIF_UseSrc0 | BIF_VariableArgsNumber              , JavascriptArray::EntryInfo::Slice)
LIBRARY_FUNCTION(Array,         Splice,             15,   BIF_UseSrc0 | BIF_VariableArgsNumber | BIF_IgnoreDst  , JavascriptArray::EntryInfo::Splice)
LIBRARY_FUNCTION(Array,         Unshift,            15,   BIF_UseSrc0 | BIF_VariableArgsNumber | BIF_IgnoreDst  , JavascriptArray::EntryInfo::Unshift)
LIBRARY_FUNCTION(Function,      Apply,              3,    BIF_UseSrc0 | BIF_IgnoreDst                           , JavascriptFunction::EntryInfo::Apply)
LIBRARY_FUNCTION(Function,      Call,               15,   BIF_UseSrc0 | BIF_IgnoreDst | BIF_VariableArgsNumber  , JavascriptFunction::EntryInfo::Call)
LIBRARY_FUNCTION(GlobalObject,  ParseInt,           1,    BIF_IgnoreDst                                         , GlobalObject::EntryInfo::ParseInt)
LIBRARY_FUNCTION(RegExp,        Exec,               2,    BIF_UseSrc0 | BIF_IgnoreDst                           , JavascriptRegExp::EntryInfo::Exec)
LIBRARY_FUNCTION(RegExp,        SymbolSearch,       2,    BIF_UseSrc0                                           , JavascriptRegExp::EntryInfo::SymbolSearch)
LIBRARY_FUNCTION(Math,          Fround,             1,    BIF_TypeSpecUnaryToFloat                              , Math::EntryInfo::Fround)
LIBRARY_FUNCTION(String,        PadStart,           2,    BIF_UseSrc0 | BIF_VariableArgsNumber                  , JavascriptString::EntryInfo::PadStart)
LIBRARY_FUNCTION(String,        PadEnd,             2,    BIF_UseSrc0 | BIF_VariableArgsNumber                  , JavascriptString::EntryInfo::PadEnd)

// Note: 1st column is currently used only for debug tracing.

// SIMD_JS
// Float32x4
LIBRARY_FUNCTION(SIMD_Float32x4,    Float32x4,         4, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Float32x4)
LIBRARY_FUNCTION(SIMD_Float32x4,    Check,             1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Float32x4,    Splat,             1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Float32x4,    ExtractLane,       2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Float32x4,    ReplaceLane,       3, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::ReplaceLane)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromInt32x4,       1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromInt32x4)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromUint32x4,      1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromUint32x4)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromInt32x4Bits,   1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromInt32x4Bits)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromInt16x8Bits,   1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromInt16x8Bits)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromInt8x16Bits,   1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromInt8x16Bits)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromUint32x4Bits,  1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromUint32x4Bits)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromUint16x8Bits,  1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromUint16x8Bits)
LIBRARY_FUNCTION(SIMD_Float32x4,    FromUint8x16Bits,  1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::FromUint8x16Bits)
LIBRARY_FUNCTION(SIMD_Float32x4,    Add,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Add)
LIBRARY_FUNCTION(SIMD_Float32x4,    Sub,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Sub)
LIBRARY_FUNCTION(SIMD_Float32x4,    Mul,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Mul)
LIBRARY_FUNCTION(SIMD_Float32x4,    Div,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Div)
LIBRARY_FUNCTION(SIMD_Float32x4,    And,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Float32x4,    Or,                2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Float32x4,    Xor,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Float32x4,    Min,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Min)
LIBRARY_FUNCTION(SIMD_Float32x4,    Max,               2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Max)
LIBRARY_FUNCTION(SIMD_Float32x4,    MinNum,            2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::MinNum)
LIBRARY_FUNCTION(SIMD_Float32x4,    MaxNum,            2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::MaxNum)
LIBRARY_FUNCTION(SIMD_Float32x4,    Abs,               1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Abs)
LIBRARY_FUNCTION(SIMD_Float32x4,    Neg,               1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Neg)
LIBRARY_FUNCTION(SIMD_Float32x4,    Not,               1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Float32x4,    Sqrt,              1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Sqrt)
LIBRARY_FUNCTION(SIMD_Float32x4,    Reciprocal,        1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Reciprocal)
LIBRARY_FUNCTION(SIMD_Float32x4,    ReciprocalSqrt,    1, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::ReciprocalSqrt)
LIBRARY_FUNCTION(SIMD_Float32x4,    LessThan,          2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::LessThan)
LIBRARY_FUNCTION(SIMD_Float32x4,    LessThanOrEqual,   2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::LessThanOrEqual)
LIBRARY_FUNCTION(SIMD_Float32x4,    Equal,             2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Equal)
LIBRARY_FUNCTION(SIMD_Float32x4,    NotEqual,          2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::NotEqual)
LIBRARY_FUNCTION(SIMD_Float32x4,    GreaterThan,       2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::GreaterThan)
LIBRARY_FUNCTION(SIMD_Float32x4,    GreaterThanOrEqual,2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::GreaterThanOrEqual)
LIBRARY_FUNCTION(SIMD_Float32x4,    Swizzle,           5, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Swizzle)
LIBRARY_FUNCTION(SIMD_Float32x4,    Shuffle,           6, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Shuffle)
LIBRARY_FUNCTION(SIMD_Float32x4,    Select,            3, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Select)
LIBRARY_FUNCTION(SIMD_Float32x4,    Load,              2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Load)
LIBRARY_FUNCTION(SIMD_Float32x4,    Load1,             2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Load1)
LIBRARY_FUNCTION(SIMD_Float32x4,    Load2,             2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Load2)
LIBRARY_FUNCTION(SIMD_Float32x4,    Load3,             2, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Load3)
LIBRARY_FUNCTION(SIMD_Float32x4,    Store,             3, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Store)
LIBRARY_FUNCTION(SIMD_Float32x4,    Store1,            3, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Store1)
LIBRARY_FUNCTION(SIMD_Float32x4,    Store2,            3, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Store2)
LIBRARY_FUNCTION(SIMD_Float32x4,    Store3,            3, BIF_IgnoreDst                                                 , SIMDFloat32x4Lib::EntryInfo::Store3)

// Int32x4
LIBRARY_FUNCTION(SIMD_Int32x4,      Int32x4,           4, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Int32x4)
LIBRARY_FUNCTION(SIMD_Int32x4,      Check,             1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Int32x4,      Splat,             1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Int32x4,      ExtractLane,       2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Int32x4,      ReplaceLane,       3, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::ReplaceLane)
LIBRARY_FUNCTION(SIMD_Int32x4,      FromFloat32x4,     1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::FromFloat32x4)
LIBRARY_FUNCTION(SIMD_Int32x4,      FromFloat32x4Bits, 1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::FromFloat32x4Bits)
LIBRARY_FUNCTION(SIMD_Int32x4,      FromInt16x8Bits,   1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::FromInt16x8Bits)
LIBRARY_FUNCTION(SIMD_Int32x4,      FromInt8x16Bits,   1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::FromInt8x16Bits)
LIBRARY_FUNCTION(SIMD_Int32x4,      FromUint32x4Bits,  1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::FromUint32x4Bits)
LIBRARY_FUNCTION(SIMD_Int32x4,      FromUint16x8Bits,  1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::FromUint16x8Bits)
LIBRARY_FUNCTION(SIMD_Int32x4,      FromUint8x16Bits,  1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::FromUint8x16Bits)
LIBRARY_FUNCTION(SIMD_Int32x4,      Add,               2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Add)
LIBRARY_FUNCTION(SIMD_Int32x4,      Sub,               2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Sub)
LIBRARY_FUNCTION(SIMD_Int32x4,      Mul,               2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Mul)
LIBRARY_FUNCTION(SIMD_Int32x4,      And,               2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Int32x4,      Or,                2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Int32x4,      Xor,               2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Int32x4,      Min,               2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Min)
LIBRARY_FUNCTION(SIMD_Int32x4,      Max,               2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Max)
LIBRARY_FUNCTION(SIMD_Int32x4,      Neg,               1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Neg)
LIBRARY_FUNCTION(SIMD_Int32x4,      Not,               1, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Int32x4,      LessThan,          2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::LessThan)
LIBRARY_FUNCTION(SIMD_Int32x4,      LessThanOrEqual,   2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::LessThanOrEqual)
LIBRARY_FUNCTION(SIMD_Int32x4,      Equal,             2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Equal)
LIBRARY_FUNCTION(SIMD_Int32x4,      NotEqual,          2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::NotEqual)
LIBRARY_FUNCTION(SIMD_Int32x4,      GreaterThan,       2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::GreaterThan)
LIBRARY_FUNCTION(SIMD_Int32x4,      GreaterThanOrEqual,2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::GreaterThanOrEqual)
LIBRARY_FUNCTION(SIMD_Int32x4,      Swizzle,           5, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Swizzle)
LIBRARY_FUNCTION(SIMD_Int32x4,      Shuffle,           6, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Shuffle)
LIBRARY_FUNCTION(SIMD_Int32x4,      ShiftLeftByScalar, 2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::ShiftLeftByScalar)
LIBRARY_FUNCTION(SIMD_Int32x4,      ShiftRightByScalar,2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::ShiftRightByScalar)
LIBRARY_FUNCTION(SIMD_Int32x4,      Select,            3, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Select)
LIBRARY_FUNCTION(SIMD_Int32x4,      Load,              2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Load)
LIBRARY_FUNCTION(SIMD_Int32x4,      Load1,             2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Load1)
LIBRARY_FUNCTION(SIMD_Int32x4,      Load2,             2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Load2)
LIBRARY_FUNCTION(SIMD_Int32x4,      Load3,             2, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Load3)
LIBRARY_FUNCTION(SIMD_Int32x4,      Store,             3, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Store)
LIBRARY_FUNCTION(SIMD_Int32x4,      Store1,            3, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Store1)
LIBRARY_FUNCTION(SIMD_Int32x4,      Store2,            3, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Store2)
LIBRARY_FUNCTION(SIMD_Int32x4,      Store3,            3, BIF_IgnoreDst                                                 , SIMDInt32x4Lib::EntryInfo::Store3)

// Int16x8
LIBRARY_FUNCTION(SIMD_Int16x8,    Int16x8,           8, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Int16x8)
LIBRARY_FUNCTION(SIMD_Int16x8,    Check,             1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Int16x8,    Splat,             1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Int16x8,    FromFloat32x4Bits, 1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::FromFloat32x4Bits)
LIBRARY_FUNCTION(SIMD_Int16x8,    FromInt32x4Bits,   1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::FromInt32x4Bits)
LIBRARY_FUNCTION(SIMD_Int16x8,    FromInt8x16Bits,   1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::FromInt8x16Bits)
LIBRARY_FUNCTION(SIMD_Int16x8,    FromUint32x4Bits,  1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::FromUint32x4Bits)
LIBRARY_FUNCTION(SIMD_Int16x8,    FromUint16x8Bits,  1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::FromUint16x8Bits)
LIBRARY_FUNCTION(SIMD_Int16x8,    FromUint8x16Bits,  1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::FromUint8x16Bits)
LIBRARY_FUNCTION(SIMD_Int16x8,    Neg,               1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Neg)
LIBRARY_FUNCTION(SIMD_Int16x8,    Not,               1, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Int16x8,    Add,               2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Add)
LIBRARY_FUNCTION(SIMD_Int16x8,    Sub,               2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Sub)
LIBRARY_FUNCTION(SIMD_Int16x8,    Mul,               2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Mul)
LIBRARY_FUNCTION(SIMD_Int16x8,    And,               2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Int16x8,    Or,                2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Int16x8,    Xor,               2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Int16x8,    AddSaturate,       2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::AddSaturate)
LIBRARY_FUNCTION(SIMD_Int16x8,    SubSaturate,       2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::SubSaturate)
LIBRARY_FUNCTION(SIMD_Int16x8,    Min,               2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Min)
LIBRARY_FUNCTION(SIMD_Int16x8,    Max,               2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Max)
LIBRARY_FUNCTION(SIMD_Int16x8,    LessThan,          2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::LessThan)
LIBRARY_FUNCTION(SIMD_Int16x8,    LessThanOrEqual,   2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::LessThanOrEqual)
LIBRARY_FUNCTION(SIMD_Int16x8,    Equal,             2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Equal)
LIBRARY_FUNCTION(SIMD_Int16x8,    NotEqual,          2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::NotEqual)
LIBRARY_FUNCTION(SIMD_Int16x8,    GreaterThan,       2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::GreaterThan)
LIBRARY_FUNCTION(SIMD_Int16x8,    GreaterThanOrEqual,2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::GreaterThanOrEqual)
LIBRARY_FUNCTION(SIMD_Int16x8,    ExtractLane,       2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Int16x8,    ReplaceLane,       3, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::ReplaceLane)
LIBRARY_FUNCTION(SIMD_Int16x8,    ShiftLeftByScalar, 2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::ShiftLeftByScalar)
LIBRARY_FUNCTION(SIMD_Int16x8,    ShiftRightByScalar,2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::ShiftRightByScalar)
LIBRARY_FUNCTION(SIMD_Int16x8,    Load,              2, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Load)
LIBRARY_FUNCTION(SIMD_Int16x8,    Store,             3, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Store)
LIBRARY_FUNCTION(SIMD_Int16x8,    Swizzle,           9, BIF_IgnoreDst                                                   , SIMDInt16x8Lib::EntryInfo::Swizzle)
LIBRARY_FUNCTION(SIMD_Int16x8,    Shuffle,           10, BIF_IgnoreDst                                                  , SIMDInt16x8Lib::EntryInfo::Shuffle)
LIBRARY_FUNCTION(SIMD_Int16x8,    Select,             3, BIF_IgnoreDst                                                  , SIMDInt16x8Lib::EntryInfo::Select)

// Int8x16
LIBRARY_FUNCTION(SIMD_Int8x16,    Int8x16,          16, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Int8x16)
LIBRARY_FUNCTION(SIMD_Int8x16,    Check,             1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Int8x16,    Splat,             1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Int8x16,    FromFloat32x4Bits, 1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::FromFloat32x4Bits)
LIBRARY_FUNCTION(SIMD_Int8x16,    FromInt32x4Bits,   1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::FromInt32x4Bits)
LIBRARY_FUNCTION(SIMD_Int8x16,    FromInt16x8Bits,   1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::FromInt16x8Bits)
LIBRARY_FUNCTION(SIMD_Int8x16,    FromUint32x4Bits,  1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::FromUint32x4Bits)
LIBRARY_FUNCTION(SIMD_Int8x16,    FromUint16x8Bits,  1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::FromUint16x8Bits)
LIBRARY_FUNCTION(SIMD_Int8x16,    FromUint8x16Bits,  1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::FromUint8x16Bits)
LIBRARY_FUNCTION(SIMD_Int8x16,    Neg,               1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Neg)
LIBRARY_FUNCTION(SIMD_Int8x16,    Not,               1, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Int8x16,    Add,               2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Add)
LIBRARY_FUNCTION(SIMD_Int8x16,    Sub,               2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Sub)
LIBRARY_FUNCTION(SIMD_Int8x16,    Mul,               2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Mul)
LIBRARY_FUNCTION(SIMD_Int8x16,    And,               2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Int8x16,    Or,                2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Int8x16,    Xor,               2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Int8x16,    AddSaturate,       2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::AddSaturate)
LIBRARY_FUNCTION(SIMD_Int8x16,    SubSaturate,       2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::SubSaturate)
LIBRARY_FUNCTION(SIMD_Int8x16,    Min,               2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Min)
LIBRARY_FUNCTION(SIMD_Int8x16,    Max,               2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Max)
LIBRARY_FUNCTION(SIMD_Int8x16,    LessThan,          2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::LessThan)
LIBRARY_FUNCTION(SIMD_Int8x16,    LessThanOrEqual,   2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::LessThanOrEqual)
LIBRARY_FUNCTION(SIMD_Int8x16,    Equal,             2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Equal)
LIBRARY_FUNCTION(SIMD_Int8x16,    NotEqual,          2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::NotEqual)
LIBRARY_FUNCTION(SIMD_Int8x16,    GreaterThan,       2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::GreaterThan)
LIBRARY_FUNCTION(SIMD_Int8x16,    GreaterThanOrEqual,2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::GreaterThanOrEqual)
LIBRARY_FUNCTION(SIMD_Int8x16,    ExtractLane,       2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Int8x16,    ReplaceLane,       3, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::ReplaceLane)
LIBRARY_FUNCTION(SIMD_Int8x16,    ShiftLeftByScalar, 2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::ShiftLeftByScalar)
LIBRARY_FUNCTION(SIMD_Int8x16,    ShiftRightByScalar,2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::ShiftRightByScalar)
LIBRARY_FUNCTION(SIMD_Int8x16,    Load,              2, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Load)
LIBRARY_FUNCTION(SIMD_Int8x16,    Store,             3, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Store)
LIBRARY_FUNCTION(SIMD_Int8x16,    Swizzle,           17, BIF_IgnoreDst                                                   , SIMDInt8x16Lib::EntryInfo::Swizzle)
LIBRARY_FUNCTION(SIMD_Int8x16,    Shuffle,           18, BIF_IgnoreDst                                                  , SIMDInt8x16Lib::EntryInfo::Shuffle)
LIBRARY_FUNCTION(SIMD_Int8x16,    Select,             3, BIF_IgnoreDst                                                  , SIMDInt8x16Lib::EntryInfo::Select)

//Uint32x4
LIBRARY_FUNCTION(SIMD_Uint32x4,    Uint32x4,            4, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Uint32x4)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Check,               1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Splat,               1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Uint32x4,    ExtractLane,         2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Uint32x4,    ReplaceLane,         3, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::ReplaceLane)
LIBRARY_FUNCTION(SIMD_Uint32x4,    FromFloat32x4,       1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::FromFloat32x4)
LIBRARY_FUNCTION(SIMD_Uint32x4,    FromFloat32x4Bits,   1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::FromFloat32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint32x4,    FromInt32x4Bits,     1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::FromInt32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint32x4,    FromInt16x8Bits,     1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::FromInt16x8Bits)
LIBRARY_FUNCTION(SIMD_Uint32x4,    FromInt8x16Bits,     1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::FromInt8x16Bits)
LIBRARY_FUNCTION(SIMD_Uint32x4,    FromUint16x8Bits,    1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::FromUint16x8Bits)
LIBRARY_FUNCTION(SIMD_Uint32x4,    FromUint8x16Bits,    1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::FromUint8x16Bits)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Not,                 1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Neg,                 1, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Neg)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Add,                 2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Add)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Sub,                 2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Sub)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Mul,                 2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Mul)
LIBRARY_FUNCTION(SIMD_Uint32x4,    And,                 2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Or,                  2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Xor,                 2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Uint32x4,    LessThan,            2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::LessThan)
LIBRARY_FUNCTION(SIMD_Uint32x4,    LessThanOrEqual,     2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::LessThanOrEqual)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Equal,               2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Equal)
LIBRARY_FUNCTION(SIMD_Uint32x4,    NotEqual,            2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::NotEqual)
LIBRARY_FUNCTION(SIMD_Uint32x4,    GreaterThan,         2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::GreaterThan)
LIBRARY_FUNCTION(SIMD_Uint32x4,    GreaterThanOrEqual,  2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::GreaterThanOrEqual)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Min,                 2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Min)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Max,                 2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Max)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Swizzle,             5, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Swizzle)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Shuffle,             6, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Shuffle)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Select,              3, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Select)
LIBRARY_FUNCTION(SIMD_Uint32x4,    ShiftLeftByScalar,   2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::ShiftLeftByScalar)
LIBRARY_FUNCTION(SIMD_Uint32x4,    ShiftRightByScalar,  2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::ShiftRightByScalar)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Load,                2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Load)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Load1,               2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Load1)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Load2,               2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Load2)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Load3,               2, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Load3)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Store,               3, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Store)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Store1,              3, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Store1)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Store2,              3, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Store2)
LIBRARY_FUNCTION(SIMD_Uint32x4,    Store3,              3, BIF_IgnoreDst                                                , SIMDUint32x4Lib::EntryInfo::Store3)

// Uint16x8
LIBRARY_FUNCTION(SIMD_Uint16x8,    Uint16x8,          8, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Uint16x8)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Check,             1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Splat,             1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Uint16x8,    FromFloat32x4Bits, 1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::FromFloat32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint16x8,    FromInt32x4Bits,   1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::FromInt32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint16x8,    FromInt16x8Bits,   1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::FromInt16x8Bits)
LIBRARY_FUNCTION(SIMD_Uint16x8,    FromInt8x16Bits,   1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::FromInt8x16Bits)
LIBRARY_FUNCTION(SIMD_Uint16x8,    FromUint32x4Bits,  1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::FromUint32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint16x8,    FromUint8x16Bits,  1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::FromUint8x16Bits)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Neg,               1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Neg)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Not,               1, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Add,               2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Add)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Sub,               2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Sub)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Mul,               2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Mul)
LIBRARY_FUNCTION(SIMD_Uint16x8,    And,               2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Or,                2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Xor,               2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Uint16x8,    AddSaturate,       2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::AddSaturate)
LIBRARY_FUNCTION(SIMD_Uint16x8,    SubSaturate,       2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::SubSaturate)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Min,               2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Min)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Max,               2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Max)
LIBRARY_FUNCTION(SIMD_Uint16x8,    LessThan,          2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::LessThan)
LIBRARY_FUNCTION(SIMD_Uint16x8,    LessThanOrEqual,   2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::LessThanOrEqual)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Equal,             2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Equal)
LIBRARY_FUNCTION(SIMD_Uint16x8,    NotEqual,          2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::NotEqual)
LIBRARY_FUNCTION(SIMD_Uint16x8,    GreaterThan,       2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::GreaterThan)
LIBRARY_FUNCTION(SIMD_Uint16x8,    GreaterThanOrEqual,2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::GreaterThanOrEqual)
LIBRARY_FUNCTION(SIMD_Uint16x8,    ExtractLane,       2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Uint16x8,    ReplaceLane,       3, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::ReplaceLane)
LIBRARY_FUNCTION(SIMD_Uint16x8,    ShiftLeftByScalar, 2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::ShiftLeftByScalar)
LIBRARY_FUNCTION(SIMD_Uint16x8,    ShiftRightByScalar,2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::ShiftRightByScalar)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Load,              2, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Load)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Store,             3, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Store)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Swizzle,           9, BIF_IgnoreDst                                                   , SIMDUint16x8Lib::EntryInfo::Swizzle)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Shuffle,           10, BIF_IgnoreDst                                                  , SIMDUint16x8Lib::EntryInfo::Shuffle)
LIBRARY_FUNCTION(SIMD_Uint16x8,    Select,            3, BIF_IgnoreDst                                                  , SIMDUint16x8Lib::EntryInfo::Select)

// Uint8x16
LIBRARY_FUNCTION(SIMD_Uint8x16,    Uint8x16,        16, BIF_IgnoreDst                                                   , SIMDUint8x16Lib::EntryInfo::Uint8x16)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Check,             1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Splat,             1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Uint8x16,    FromFloat32x4Bits, 1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::FromFloat32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint8x16,    FromInt32x4Bits,   1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::FromInt32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint8x16,    FromInt16x8Bits,   1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::FromInt16x8Bits)
LIBRARY_FUNCTION(SIMD_Uint8x16,    FromInt8x16Bits,   1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::FromInt8x16Bits)
LIBRARY_FUNCTION(SIMD_Uint8x16,    FromUint32x4Bits,  1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::FromUint32x4Bits)
LIBRARY_FUNCTION(SIMD_Uint8x16,    FromUint16x8Bits,  1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::FromUint16x8Bits)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Neg,               1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Neg)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Not,               1, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Add,               2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Add)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Sub,               2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Sub)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Mul,               2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Mul)
LIBRARY_FUNCTION(SIMD_Uint8x16,    And,               2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Or,                2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Xor,               2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Uint8x16,    AddSaturate,       2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::AddSaturate)
LIBRARY_FUNCTION(SIMD_Uint8x16,    SubSaturate,       2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::SubSaturate)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Min,               2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Min)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Max,               2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Max)
LIBRARY_FUNCTION(SIMD_Uint8x16,    LessThan,          2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::LessThan)
LIBRARY_FUNCTION(SIMD_Uint8x16,    LessThanOrEqual,   2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::LessThanOrEqual)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Equal,             2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Equal)
LIBRARY_FUNCTION(SIMD_Uint8x16,    NotEqual,          2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::NotEqual)
LIBRARY_FUNCTION(SIMD_Uint8x16,    GreaterThan,       2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::GreaterThan)
LIBRARY_FUNCTION(SIMD_Uint8x16,    GreaterThanOrEqual,2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::GreaterThanOrEqual)
LIBRARY_FUNCTION(SIMD_Uint8x16,    ExtractLane,       2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Uint8x16,    ReplaceLane,       3, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::ReplaceLane)
LIBRARY_FUNCTION(SIMD_Uint8x16,    ShiftLeftByScalar, 2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::ShiftLeftByScalar)
LIBRARY_FUNCTION(SIMD_Uint8x16,    ShiftRightByScalar,2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::ShiftRightByScalar)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Load,              2, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Load)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Store,             3, BIF_IgnoreDst                                                  , SIMDUint8x16Lib::EntryInfo::Store)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Swizzle,           17, BIF_IgnoreDst                                                 , SIMDUint8x16Lib::EntryInfo::Swizzle)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Shuffle,           18, BIF_IgnoreDst                                                 , SIMDUint8x16Lib::EntryInfo::Shuffle)
LIBRARY_FUNCTION(SIMD_Uint8x16,    Select,             3, BIF_IgnoreDst                                                 , SIMDUint8x16Lib::EntryInfo::Select)

// Bool32x4
LIBRARY_FUNCTION(SIMD_Bool32x4,    Bool32x4,           4, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::Bool32x4)
LIBRARY_FUNCTION(SIMD_Bool32x4,    Check,              1, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Bool32x4,    Splat,              1, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Bool32x4,    Not,                1, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Bool32x4,    AllTrue,            1, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::AllTrue)
LIBRARY_FUNCTION(SIMD_Bool32x4,    AnyTrue,            1, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::AnyTrue)
LIBRARY_FUNCTION(SIMD_Bool32x4,    And,                2, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Bool32x4,    Or,                 2, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Bool32x4,    Xor,                2, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Bool32x4,    ExtractLane,        2, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Bool32x4,    ReplaceLane,        3, BIF_IgnoreDst                                                 , SIMDBool32x4Lib::EntryInfo::ReplaceLane)

// Bool16x8
LIBRARY_FUNCTION(SIMD_Bool16x8,    Bool16x8,           8, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::Bool16x8)
LIBRARY_FUNCTION(SIMD_Bool16x8,    Check,              1, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Bool16x8,    Splat,              1, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Bool16x8,    Not,                1, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Bool16x8,    AllTrue,            1, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::AllTrue)
LIBRARY_FUNCTION(SIMD_Bool16x8,    AnyTrue,            1, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::AnyTrue)
LIBRARY_FUNCTION(SIMD_Bool16x8,    And,                2, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Bool16x8,    Or,                 2, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Bool16x8,    Xor,                2, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Bool16x8,    ExtractLane,        2, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Bool16x8,    ReplaceLane,        3, BIF_IgnoreDst                                                 , SIMDBool16x8Lib::EntryInfo::ReplaceLane)

// Bool8x16
LIBRARY_FUNCTION(SIMD_Bool8x16,    Bool8x16,          16, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::Bool8x16)
LIBRARY_FUNCTION(SIMD_Bool8x16,    Check,              1, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::Check)
LIBRARY_FUNCTION(SIMD_Bool8x16,    Splat,              1, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::Splat)
LIBRARY_FUNCTION(SIMD_Bool8x16,    Not,                1, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::Not)
LIBRARY_FUNCTION(SIMD_Bool8x16,    AllTrue,            1, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::AllTrue)
LIBRARY_FUNCTION(SIMD_Bool8x16,    AnyTrue,            1, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::AnyTrue)
LIBRARY_FUNCTION(SIMD_Bool8x16,    And,                2, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::And)
LIBRARY_FUNCTION(SIMD_Bool8x16,    Or,                 2, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::Or)
LIBRARY_FUNCTION(SIMD_Bool8x16,    Xor,                2, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::Xor)
LIBRARY_FUNCTION(SIMD_Bool8x16,    ExtractLane,        2, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::ExtractLane)
LIBRARY_FUNCTION(SIMD_Bool8x16,    ReplaceLane,        3, BIF_IgnoreDst                                                 , SIMDBool8x16Lib::EntryInfo::ReplaceLane)
