;;-------------------------------------------------------------------------------------------------------
;; Copyright (C) Microsoft Corporation and contributors. All rights reserved.
;; Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
;;-------------------------------------------------------------------------------------------------------

(module
    (import "dummy" "memory" (memory 1))

        (func (export "m128_const_1") (local $v1 m128)
            (set_local $v1 
            (m128.const 
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0) 
                (i32.const 0xcc)
                (i32.const 0xab)
                (i32.const 0x0)
                (i32.const 0xff)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0) 
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
            )
            )
            (m128.store offset=0 (i32.const 0) (get_local $v1))
        )

        (func (export "m128_const_2") (local $v1 m128)
            (set_local $v1 
            (m128.const 
                (i32.const 0x0)
                (i32.const 0xbc)
                (i32.const 0x0)
                (i32.const 0xa1)
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff) 
                (i32.const 0x0)
                (i32.const 0xff)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x1)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
            )
            )
            (m128.store offset=0 (i32.const 0) (get_local $v1))
        )

        (func (export "m128_const_3") (local $v1 m128)
            (set_local $v1 
            (m128.const 
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff) 
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff) 
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0) 
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff)
                (i32.const 0xff)
            )
            )
            (m128.store offset=0 (i32.const 0) (get_local $v1))
        )

        (func (export "m128_const_4") (local $v1 m128)
            (set_local $v1 
            (m128.const 
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
                (i32.const 0x0)
            )
            )
            (m128.store offset=0 (i32.const 0) (get_local $v1))
        )
)
